server:
  port: 8080

spring:
  profiles:
    include:
      - oauth
      - database
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

#logging:
#  level:
#    org.hibernate.SQL: debug